name: action

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_KEY: ${{ secrets.CLOUDINARY_KEY }}
      CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
      MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
      DB_URL: ${{ secrets.DB_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Deploy
        env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_KEY: ${{ secrets.CLOUDINARY_KEY }}
          CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
          DB_URL: ${{ secrets.DB_URL }}
        run: |
          npm run deploy
